# Generated by Django 3.1.4 on 2020-12-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user_response', models.TextField(help_text='Enter any text you like. Please do not enter any PII information.')),
            ],
        ),
    ]
